### ISSUE TITLE
Random unhandled rejection when producing

### ISSUE THREAD

**Issue by unfrgivn** [itcig/metamorphosis#13]
Cannot reproduce, but possible to force an uncaught exception when producing messages if the brokers are not yet connected

```sh
metamorphosis:error Error producing message: Error: Broker not connected 
at Broker.lookupRequest (~/node_modules/kafkajs/src/broker/index.js:64:13) 
at Broker.metadata (~/node_modules/kafkajs/src/broker/index.js:188:27) 
at ~/node_modules/kafkajs/src/cluster/brokerPool.js:127:38 
at retry (~/node_modules/kafkajs/src/retry/index.js:43:5) 
at ~/node_modules/kafkajs/src/retry/index.js:61:5 at new Promise (<anonymous>) 
at BrokerPool.retrier (~/node_modules/kafkajs/src/retry/index.js:58:10) 
at BrokerPool.refreshMetadata (~/node_modules/kafkajs/src/cluster/brokerPool.js:125:17)     
at processTicksAndRejections (internal/process/task_queues.js:94:5)
at async Cluster.refreshMetadata (~/node_modules/kafkajs/src/cluster/index.js:120:5)
```

**Comment by unfrgivn** [comment]
Removing the `throw err` in producer `sendMessages|sendBatch()` now allows the following to be caught

```
metamorphosis:error Error producing message: KafkaJSNonRetriableError Caused by: KafkaJSConnectionError: Connection timeout at Timeout.onTimeout [as _onTimeout] (~/node_modules/kafkajs/src/network/connection.js:153:23)     
at listOnTimeout (internal/timers.js:531:17)     
at processTimers (internal/timers.js:475:7) 
{
    name: 'KafkaJSNumberOfRetriesExceeded',
    retriable: false,
    helpUrl: undefined,
    originalError: KafkaJSConnectionError: Connection timeout at Timeout.onTimeout[as _onTimeout](~/ node_modules/kafkajs /src/network/connection.js: 153:23) at listOnTimeout(internal/timers.js: 531:17)
    at processTimers(internal/timers.js: 475: 7) {
        name: 'KafkaJSConnectionError',
        retriable: true,
        helpUrl: undefined,
        broker: '127.0.0.1:9092',
        code: undefined
    },
    retryCount: 5,
    retryTime: 6124
}
```

**Comment by unfrgivn** [comment]
I think this was actually a failure on the calling application try/catch and not connecting the producer before attempting to send which was creating the "lock timeouts"
